# Generated by Django 4.2.5 on 2023-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment_created_on_comment_updated_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AddField(
            model_name="post",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
