# Generated by Django 4.2.5 on 2023-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_options_post_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
