# Generated by Django 4.2.5 on 2024-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_media_thumbnail_url"),
        ("posts", "0006_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.ManyToManyField(to="media.media"),
        ),
    ]
