# Generated by Django 4.2.5 on 2023-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messageboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authorization_token",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
