# Generated by Django 4.2.5 on 2023-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messageboard", "0002_user_authorization_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
