# Generated by Django 4.2.5 on 2023-10-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messageboard", "0005_user_mastodon_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mastodon_post_count",
            field=models.IntegerField(default=0),
        ),
    ]
