# Generated by Django 4.2.5 on 2023-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messageboard", "0006_user_mastodon_post_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mastodon_registration_date",
            field=models.DateTimeField(),
        ),
    ]
